### ISSUE TITLE
Authentik LDAP Outpost Config Guide

### ISSUE THREAD

**Issue by matthewstrasiotto** [jellyfin/jellyfin-plugin-ldapauth#120]
Hi Y'all
I'm writing this to document the process of getting this plugin running aginst Authentik's LDAP Output

Jellyfin side:

```yaml
# The hostname within the docker network
# Or whatever host your outpost is on

ldap_server: ak-outpost-ldap
ldap_port: 3389

Secure_LDAP: false
StartTLS: false
skip_ssl: true

# Optional - I haven't configured this yet
# It'll be authentik.example.com/if/reset_password or something
password_reset_url: whatever

# LDAP Bind User:
bind_user: cn=admin,ou=users,dc=media,dc=straz,dc=to
bind_user_password: your_admin_password

search_base_dn: dc=media,dc=straz,dc=to

ldap_user_filter: (memberOf=cn=jellyfin_user,ou=groups,dc=media,dc=straz,dc=to)

# Leave empty
lldap_admin_base_dn: ~

lldap_admin_filter: (memberOf=cn=jellyfin_admin,ou=groups,dc=media,dc=straz,dc=to)

ldap_attributes: uid, cn, mail, displayName

enable_case_insensitive_username: true

test_login_name: whatever

enable_user_creation: true

# cn probably works too
ldap_name_attribute: uid
```

Authentik side:

Find this in the "Providers" config

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/39424834/167802107-21079f2c-0da3-4e5c-901e-e09b1f34479a.png">
