### ISSUE TITLE
Error when using IPv6: System.Net.Sockets.SocketException (113): No route to host

### ISSUE THREAD

**Issue by m00nwtchr** [jellyfin/jellyfin-plugin-ldapauth#125]
I recently turned on IPv6 support in my docker setup, including the default network for my compose project. IPv4 addresses are still available. But this resulted in the plugin being unable to connect to the openldap server with that error, both using the docker service name and directly specified IPv6 IP. The solution was to set the value to the IPv4 ip for the openldap container, which is not ideal.

**Comment by ilarrain** [comment]
I'm having the same issue. I can't use ip resolution by container name ('openldap'). Had to resort to asigning a fixed ip to he openldap container in the compose file:
```
services:
  openldap:
    container_name: openldap
    networks:
      default:
        ipv4_address: 172.30.40.60
        ipv6_address: fd43:4343:4343::60
  
networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.40.0/24
        ip_range: 172.30.40.0/26
        gateway: 172.30.40.1
      - subnet: fd43:4343:4343::/64
        gateway: fd43:4343:4343::1
```

Anyway, as you said, less than ideal.

**Comment by crobibero** [comment]
This doesn't sound like an issue with the plugin, or Jellyfin- but with Docker itself.

**Comment by Crazy3lf** [comment]
I was met by this error when trying to set it up:
```
[WRN] [40] Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin: Ldap Test Failed to Connect or Bind to server
LdapException: Unable to connect to server lldap:3890 (91) Connect Error
System.Net.Sockets.SocketException (111): Connection refused
   at Novell.Directory.Ldap.AsyncExtensions.WaitAndUnwrap(Task task, Int32 timeout)
   at Novell.Directory.Ldap.Connection.Connect(String host, Int32 port, Int32 semaphoreId)
```
I was linked here from [this forum](https://www.answeroverflow.com/m/1387468315424722976).

I had a docker network set up between my lldap and jellyfin container so I just try disabling the ipv6 on the network.
```yaml
networks:
  lldap_jellyfin:
    external: true
    enable_ipv6: false
```
With this I am able to connect successfully. 
This might not relate to this issue, or as another comment said, may not be a issue with the plugin at all. I just hope it helps if someone trying to find a solution for this error.
